### ISSUE TITLE
Emoji is not reactive

### ISSUE THREAD

**Issue by Sandip124** [BirajMainali/password-viewer#1]
Emoji is not reacting based on the input state 
in my case  there is another passowrd toggle button  which toggles the passowrd

![image](https://user-images.githubusercontent.com/37034590/173398884-fd1f339d-064e-4ad5-87d4-cce91d733d93.png)

**Comment by BirajMainali** [comment]
@Sandip124 Thanks for the issue, I appreciate it🤸
